name: Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Show server before
        run: cat /Users/rihardsindars/python-server/app.py

      - name: Copy dev to local server
        run: cp /Users/rihardsindars/python-dev/app.py /Users/rihardsindars/python-server/app.py

      - name: Show server after
        run: cat /Users/rihardsindars/python-server/app.py

      - name: Run server app
        run: python3 /Users/rihardsindars/python-server/app.py
